#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin install-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Generate wp-config.php file
generate_config ()
{
	cd ${DOCROOT_PATH}/wordpress-develop

	rm -f wp-config.php
	wp core config --dbname=${MYSQL_DATABASE} --dbuser=${MYSQL_USER} --dbpass=${MYSQL_PASSWORD} --dbhost=db --extra-php <<PHP
// Allow (src|build).develop.wp to share the same Database
if ( isset( \$_SERVER['HTTP_HOST'] ) && 'build.develop.wp' === \$_SERVER['HTTP_HOST'] ) {
	define( 'WP_HOME', 'http://build.develop.wp' );
	define( 'WP_SITEURL', 'http://build.develop.wp' );
}
define( 'WP_DEBUG', true );
PHP
	mv src/wp-config.php wp-config.php
}

# Install site
site_install ()
{
	cd ${DOCROOT_PATH}/wordpress-develop/src

	# Install WordPress
	wp core install \
		--url=src.${VIRTUAL_HOST} \
		--title='WordPress Develop' \
		--admin_user=${WP_ADMIN_USER} \
		--admin_password=${WP_ADMIN_PASS} \
		--admin_email=${WP_ADMIN_EMAIL}
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
echo -e "${green}Generating wp-config.php...${NC}"
generate_config

echo -e "${green}Setting up database...${NC}"
site_install

#-------------------------- END: Execution --------------------------------
